### ISSUE TITLE
Страница логина ломается, если передан слишком длинный логин

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLab4#1]

**Comment by joseortiz9** [comment]
https://github.com/joseortiz9/WebLab4/blob/acfbd3606db74bf33508b17adc162b299ce91161/backend-api/src/main/java/ru/students/lab/weblab4/payload/AuthRequest.java#L9

https://github.com/joseortiz9/WebLab4/blob/acfbd3606db74bf33508b17adc162b299ce91161/backend-api/src/main/java/ru/students/lab/weblab4/exceptions/GlobalExceptionHandler.java#L31

corrected api response for the hibernate validators
