### ISSUE TITLE
Название не соответствует REST'у

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLab4#4]
https://github.com/joseortiz9/WebLab4/blob/dee997b02f445bfb7029f0ccf89556ab252b9d0f/backend-api/src/main/java/ru/students/lab/weblab4/controllers/PointController.java#L32

**Comment by joseortiz9** [comment]
https://github.com/joseortiz9/WebLab4/blob/acfbd3606db74bf33508b17adc162b299ce91161/backend-api/src/main/java/ru/students/lab/weblab4/controllers/PointController.java#L32
corrected
